# TCL File Generated by Component Editor 21.1
# Sun Feb 23 22:19:52 CET 2025
# DO NOT MODIFY


# 
# AvalonI2S "AvalonI2S" v1.0
# zorkzorkus 2025.02.23.22:19:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AvalonI2S
# 
set_module_property DESCRIPTION ""
set_module_property NAME AvalonI2S
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ZorkCores
set_module_property AUTHOR zorkzorkus
set_module_property DISPLAY_NAME AvalonI2S
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AvalonI2S
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AvalonI2S.vhd VHDL PATH AvalonI2S.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BUFFER_BITLENGTH NATURAL 5
set_parameter_property BUFFER_BITLENGTH DEFAULT_VALUE 5
set_parameter_property BUFFER_BITLENGTH DISPLAY_NAME BUFFER_BITLENGTH
set_parameter_property BUFFER_BITLENGTH TYPE NATURAL
set_parameter_property BUFFER_BITLENGTH UNITS None
set_parameter_property BUFFER_BITLENGTH ALLOWED_RANGES 0:2147483647
set_parameter_property BUFFER_BITLENGTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point system_clock
# 
add_interface system_clock clock end
set_interface_property system_clock clockRate 0
set_interface_property system_clock ENABLED true
set_interface_property system_clock EXPORT_OF ""
set_interface_property system_clock PORT_NAME_MAP ""
set_interface_property system_clock CMSIS_SVD_VARIABLES ""
set_interface_property system_clock SVD_ADDRESS_GROUP ""

add_interface_port system_clock clk_sys clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock system_clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink resetn reset_n Input 1


# 
# connection point avalon
# 
add_interface avalon avalon end
set_interface_property avalon addressUnits WORDS
set_interface_property avalon associatedClock system_clock
set_interface_property avalon associatedReset reset_sink
set_interface_property avalon bitsPerSymbol 8
set_interface_property avalon burstOnBurstBoundariesOnly false
set_interface_property avalon burstcountUnits WORDS
set_interface_property avalon explicitAddressSpan 0
set_interface_property avalon holdTime 0
set_interface_property avalon linewrapBursts false
set_interface_property avalon maximumPendingReadTransactions 0
set_interface_property avalon maximumPendingWriteTransactions 0
set_interface_property avalon readLatency 0
set_interface_property avalon readWaitTime 1
set_interface_property avalon setupTime 0
set_interface_property avalon timingUnits Cycles
set_interface_property avalon writeWaitTime 0
set_interface_property avalon ENABLED true
set_interface_property avalon EXPORT_OF ""
set_interface_property avalon PORT_NAME_MAP ""
set_interface_property avalon CMSIS_SVD_VARIABLES ""
set_interface_property avalon SVD_ADDRESS_GROUP ""

add_interface_port avalon avalon_address address Input 3
add_interface_port avalon avalon_writedata writedata Input 32
add_interface_port avalon avalon_write write Input 1
add_interface_port avalon avalon_read read Input 1
add_interface_port avalon avalon_readdata readdata Output 32
add_interface_port avalon avalon_waitrequest waitrequest Output 1
set_interface_assignment avalon embeddedsw.configuration.isFlash 0
set_interface_assignment avalon embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock system_clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender avalon_irq irq Output 1


# 
# connection point i2s_clock
# 
add_interface i2s_clock clock end
set_interface_property i2s_clock clockRate 0
set_interface_property i2s_clock ENABLED true
set_interface_property i2s_clock EXPORT_OF ""
set_interface_property i2s_clock PORT_NAME_MAP ""
set_interface_property i2s_clock CMSIS_SVD_VARIABLES ""
set_interface_property i2s_clock SVD_ADDRESS_GROUP ""

add_interface_port i2s_clock clk_i2s clk Input 1


# 
# connection point i2s
# 
add_interface i2s conduit end
set_interface_property i2s associatedClock system_clock
set_interface_property i2s associatedReset ""
set_interface_property i2s ENABLED true
set_interface_property i2s EXPORT_OF ""
set_interface_property i2s PORT_NAME_MAP ""
set_interface_property i2s CMSIS_SVD_VARIABLES ""
set_interface_property i2s SVD_ADDRESS_GROUP ""

add_interface_port i2s i2s_dati dati Input 1
add_interface_port i2s i2s_dato dato Output 1
add_interface_port i2s i2s_mclk mclk Output 1
add_interface_port i2s i2s_sclk sclk Output 1
add_interface_port i2s i2s_wclk wclk Output 1

